
export type Language = 'en' | 'bn';

export const TRANSLATIONS = {
  en: {
    appName: "FuelGuard Setabganj",
    welcomeBack: "Authorized Personnel Login",
    loginSubtitle: "Scan your credentials or authenticate via digital channel",
    userManual: "User Guidelines",
    register: "Register Vehicle",
    helpline: "Official Helpline",
    getQrWithOtp: "Authorize Fuel Pass",
    phoneNumber: "Mobile Number",
    registrationNumber: "Registration Number",
    confirmPassword: "Confirm Password",
    email: "Email Address",
    fullName: "Full Name",
    passwordMismatch: "Passwords do not match",
    passwordWeak: "Password must be at least 8 characters",
    password: "Password",
    forgotPassword: "Forgot password?",
    signIn: "Sign In",
    noAccount: "Don't have an account?",
    nbTitle: "7-Day Restriction Protocol",
    nbText: "Fuel consumption is regulated via 7-day restriction protocol. Please ensure your digital permit is valid before arrival.",
    divisionName: "Bochaganj Administration",
    consumerManual: "Consumer Web Manual",
    privacyPolicy: "Privacy Policy",
    copyright: "© 2026 FuelGuard Setabganj. All rights reserved",
    dashboard: "Dashboard",
    registry: "Registry",
    pricing: "Pricing",
    exit: "Exit",
    logout: "Log Out",
    terminal: "Terminal v3.1",
    heroTitle: "Fuel Control & Monitoring System",
    heroDesc: "Regulating Petrol & Octane consumption for motorcycles and motor vehicles across 5 fuel stations in Setabganj.",
    terminals: "Terminals",
    nodes: "Nodes",
    protocol: "Protocol",
    identityTerminal: "Identity Terminal",
    secureGateway: "Secure Access Gateway",
    fullIdentity: "Full Identity",
    dataIndex: "Data Index (Email)",
    passkey: "Passkey",
    authorize: "Authorize Identity",
    initialize: "Initialize Registry",
    encryptionBridge: "Encryption Bridge",
    googleSso: "SAML / Google SSO",
    newRegistry: "Create New Registry Profile",
    returningPersonnel: "Returning Personnel? Sign In",
    protocolGuide: "Protocol Guide",
    operationalWorkflow: "Operational Workflow",
    step1Title: "Identity Registry",
    step1Desc: "Users must submit NID and Vehicle credentials. Administrators verify documentation before granting \"Approved\" status for fuel collection.",
    step2Title: "QR Token Emission",
    step2Desc: "Approved profiles generate unique encrypted QR tokens. These tokens carry identity and cooldown status data for station terminal scanners.",
    step3Title: "Dynamic Cooldown",
    step3Desc: "Linear cooldown logic: 100 BDT = 1 Day. System prevents overproduction and manages regional fuel reserves.",
    monitoringNode: "Centralized Monitoring Node",
    monitoringDesc: "Super Admins maintain a live synchronization layer across all 4 pump stations. Every transaction is indexed by Vehicle ID, Terminal ID, and Dispensing Personnel.",
    latestTransactions: "Latest Transaction Logs",
    availableLimit: "Available Limit",
    totalActiveVehicles: "Total Active Vehicles",
    scanQr: "Scan vehicle QR",
    theme: "Theme",
    switchToLight: "Switch to Light mode",
    switchToDark: "Switch to Dark mode",
    statusAvailable: "Available",
    successAvailable: "Success Available",
    driverName: "Driver Name",
    timestamp: "Timestamp",
    quantityLiters: "Quantity (Liters)",
    recentTransactionFeed: "Recent Transaction Feed",
    criticalSystemAlerts: "Critical System Alerts",
    appUptime: "Appuptime",
    latency: "Latency",
    centralMonitoringNode: "Central Monitoring Node",
    step1Landing: "Register/Onboarding",
    step2Landing: "Verify and Information",
    step3Landing: "Fill and Complete",
    globalStatus: "Global Network Status",
    activeNodes: "Active Nodes",
    systemPerformance: "System Performance",
    viewDashboard: "View Dashboard",
    globalEfficiency: "Global Efficiency",
    uptime: "Terminal Uptime Sync",
    privacy: "Privacy Protocol",
    securityAudit: "Security Audit",
    requirementsTitle: "Required Documents for Registration",
    reqItem1: "Driving License or Vehicle Registration (Any one is mandatory)",
    reqItem2: "National Identity Card (NID)",
    reqItem3: "Passport size photo",
    reqItem4: "Fuel application form with driver's name, NID, and driving license/registration (Available at computer shops)",
    reqItem5: "Proof of employment for those working in Bochaganj institutions (ID Card, etc.)",
    appLocationTitle: "Application Submission Guidelines",
    locMunicipality: "Pourashava area -> Apply to Pourashava Office",
    locUnion123: "Union 1, 2, 3 -> Apply to UNO Office",
    locUnion456: "Union 4, 5, 6 -> Apply to Land Office (AC Land)",
    contactAdmin: "Contact Admin",
    adminName: "Md. Maruf Hasan",
    adminTitle: "Upazila Nirbahi Officer (UNO)",
    adminMobile: "01761-493526",
    adminPhone: "05325-73009",
    adminEmail: "unobochaganj@gov.bd",
    supportMessenger: "Support Messenger",
    facebookProfile: "Facebook Profile",
    facebookMessengerLink: "https://www.facebook.com/messages/t/61564992836491",
    facebookProfileLink: "https://www.facebook.com/upajela.nirbahi.aphisara.bocaganja",
    myDigitalToken: "My Digital Token",
    readyForCollection: "Ready for Collection",
    initializing: "Initializing...",
    waitForApproval: "Wait for Approval",
    scanDescription: "Present this encrypted QR at any of the 4 station terminals. Personnel will verify your data index and dispense fuel.",
    timeRemaining: "Time Remaining",
    minutes: "minutes",
    profile: "Profile",
    scanner: "Scanner",
    admin: "Admin",
    logs: "Logs",
    unauthorized: "Unauthorized Identity",
    unapprovedDesc: "Your clearance is currently pending server authorization. Please contact the Bochaganj Upazila Nirbahi Officer (UNO) for manual override.",
    systemStatus: "System status: Operational",
    finalizeProfile: "Finalize Registry Profile",
    nidNumber: "NID Number",
    vehicleIndex: "Vehicle Index",
    submitProfile: "Authorize Registry Data",
    personnelRegistry: "Personnel Registry",
    personnelRegistryDesc: "Central repository of all approved fuel recipients and logistics personnel.",
    rankMatrix: "Personnel Rank Matrix",
    pricingControl: "Dynamic Pricing Control",
    manageUsers: "Manage Users",
    manageStations: "Manage Stations",
    pendingApprovals: "Pending Approvals",
    priceQuotes: "Price Quotes",
    completeRegistration: "Complete Registration",
    vehiclePlate: "Vehicle License Plate",
    platePlaceholder: "e.g. Dhaka-Metro-Ga-11-2222",
    adminReviewNote: "Note: Admin will review your credentials before terminal activation.",
    submitForApproval: "Submit for Approval",
    userDigitalId: "User Digital ID",
    approvedStatus: "APPROVED",
    pendingStatus: "PENDING",
    registryId: "Registry ID",
    validFrom: "Valid From",
    scannerLogic: "Scanner Logic",
    accessDenied: "Access Denied",
    systemReady: "System Ready",
    remaining: "Remaining",
    days: "Days",
    awaitingApproval: "Awaiting Approval",
    adminReviewDesc: "The Upazila Nirbahi Officer (UNO) must verify documents before terminal activation.",
    cooldownActive: "COOLDOWN ACTIVE",
    nextRefillOn: "Next refill available on",
    ruleCooldown: "Rule: 100 BDT = 1 Day Limit",
    terminalStatus: "Terminal Status",
    active: "ACTIVE",
    scannerHint: "Scanner will accept Digital ID for refill.",
    dailyPricingMatrix: "Daily Pricing Matrix",
    octaneBdt: "Octane / BDT",
    petrolBdt: "Petrol / BDT",
    dieselBdt: "Diesel / BDT",
    stationTerminalControl: "Station Terminal Control",
    terminalLocation: "Terminal Location",
    unassigned: "-- UNASSIGNED --",
    activateQrScanner: "Activate QR Scanner",
    scanStatus: "Scan Status",
    locked: "LOCKED",
    resetTerminal: "Reset Terminal",
    refillRecorded: "Refill Recorded",
    nextVehicle: "Next Vehicle",
    identityVerified: "Identity Verified",
    inputAmountBdt: "Input Amount (BDT)",
    transmitLogRefill: "Transmit & Log Refill",
    radarStandby: "Radar Standby",
    waitingForScan: "Waiting for terminal scanning event...",
    statusReports: "Status Reports",
    registryHub: "Registry Hub",
    priceConfig: "Price Config",
    analytics: "Analytics",
    updatePrices: "Update Prices",
    currentPrices: "Current Prices",
    fuelType: "Fuel Type",
    priceBdt: "Price (BDT)",
    octanePrice: "Octane Price",
    petrolPrice: "Petrol Price",
    dieselPrice: "Diesel Price",
    userRoleHub: "User Role Hub",
    approvalQueue: "Approval Queue",
    actions: "Actions",
    approve: "Approve",
    alreadyApproved: "Already Approved",
    role: "Role",
    update: "Update",
    changeRole: "Change Role",
    userRegistry: "User Registry",
    deleteAccount: "Delete Account",
    superAdminAccess: "Super Admin Access Required",
    addPump: "Add New Pump Station",
    addressLabel: "Station Address",
    geoLocLabel: "Geographic Location",
    syncEstLabel: "Est. Synchronization",
    pumpName: "Pump Name",
    deliveryDate: "Next Delivery Date",
    savePump: "Save Station",
    provisionPersonnel: "Provision Personnel",
    emailPlaceholder: "official@station.com",
    manualAdd: "Pre-Authorize Email",
    toastSuccess: "Operation Successful",
    toastError: "System Error",
    lastDelivery: "Last Delivery",
    offline: "OFFLINE",
    fuelPriceUpdate: "Fuel Price Update",
    deployPricing: "Deploy Pricing",
    manualProvisioning: "Manual Provisioning",
    grantAccess: "Grant Access",
    stationTerminals: "Station Terminals",
    adminLogin: "Admin Login",
    userLogin: "User Portal",
    idPlaceholder: "Official Email / Govt ID",
    passPlaceholder: "Encryption Key / Password",
    loginAsAdmin: "Authenticate as Admin",
    backToUser: "Back to User Portal",
    adminAccessPortal: "Admin Access Portal",
    allUsers: "Citizen Registry",
    transactions: "Service Logs",
    managePrices: "Price Control",
    allTransactions: "Detailed Transaction History",
    filterByStation: "Filter by Station",
    filterByUser: "Filter by User",
    dailyUsage: "Daily Usage & Quota",
    monthlyUsage: "Monthly Usage & Quota",
    weeklyUsage: "Weekly Usage",
    currentQr: "Current QR Code",
    createQr: "Create QR Code",
    viewAll: "View All",
    availableStations: "Available Fuel Stations",
    viewOnMap: "View on Map",
    lastStockUpdate: "Last Stock Update",
    pendingApprovalTitle: "Account Pending Approval",
    pendingApprovalDesc: "Your registration is being reviewed by the Bochaganj Upazila Nilbari Officer (UNO) office. Please wait for authorization.",
    waitingTime: "Usually takes 24-48 hours",
    contactSupport: "Contact UNO Office",
    last7Days: "Last 7 Days Usage",
    liters: "Liters",
    registrationNumberShort: "Reg No.",
    manufactureYearShort: "Year",
    vehicleClassShort: "Class",
    houseHolding: "House/Holding",
    villageStreet: "Village/Street",
    postOffice: "Post Office",
    revokeAccess: "Revoke Access",
    confirmRevoke: "Are you sure you want to revoke this user's access?",
    filterByFuel: "Filter by Fuel",
    allFuels: "All Fuels",
    octane: "Octane",
    petrol: "Petrol",
    diesel: "Diesel",
    uploadProfilePhoto: "Upload Profile Photo",
    changePhoto: "Change Photo",
    registryDetails: "Details",
    userType: "User Type",
    contactInfo: "Contact Info",
    licenseInfo: "License Info",
    activity: "Activity",
    systemLogs: "System Logs",
    vehicleRegistration: "Vehicle Registration",
    vehicleRegistrationSub: "Register your motorcycle or motor vehicle for fuel monitoring at Setabganj stations.",
    licensePlate: "License Plate / Reg No",
    engineNumber: "Engine Number",
    chassisNumber: "Chassis Number",
    vehicleType: "Vehicle Type",
    drivingLicenseNo: "Driving License No",
    taxTokenNo: "Tax Token / Registration Card Number",
    createOwnerAccount: "Create Owner Account",
    uploadRequiredDocs: "Upload Required Documents (JPG/PNG)",
    passportPhoto: "Passport Size Photo",
    nidPhoto: "NID Card Photo",
    drivingLicensePhoto: "Driving License Photo",
    taxTokenPhoto: "Tax Token / Reg Card"
  },
  bn: {
    appName: "ফুয়েলগার্ড সেতাবগঞ্জ",
    welcomeBack: "অনুমোদিত কর্মী লগইন",
    loginSubtitle: "আপনার পরিচয় যাচাই করুন অথবা ডিজিটাল চ্যানেলে লগইন করুন",
    userManual: "ব্যবহারকারী ম্যানুয়াল",
    register: "যানবাহন নিবন্ধন",
    helpline: "হেল্পলাইন",
    getQrWithOtp: "ওটিপির মাধ্যমে কিউআর পান",
    phoneNumber: "ফোন নম্বর",
    registrationNumber: "রেজিস্ট্রেশন নম্বর",
    confirmPassword: "পাসওয়ার্ড নিশ্চিত করুন",
    email: "ইমেইল ঠিকানা",
    fullName: "পুরো নাম",
    passwordMismatch: "পাসওয়ার্ড দুটি মেলেনি",
    passwordWeak: "পাসওয়ার্ড কমপক্ষে ৮ অক্ষরের হতে হবে",
    password: "পাসওয়ার্ড",
    forgotPassword: "পাসওয়ার্ড ভুলে গেছেন?",
    signIn: "সাইন ইন",
    noAccount: "অ্যাকাউন্ট নেই?",
    nbTitle: "৭-দিনের ব্লক নিয়ম",
    nbText: "যানবাহনের জ্বালানি ব্যবহার নিয়ন্ত্রণের জন্য ৭ দিনের ব্লক নিয়ম। স্টেশনে আসার আগে আপনার ডিজিটাল পারমিটটি যাচাই করে নিন।",
    divisionName: "বোচাগঞ্জ প্রশাসন",
    consumerManual: "ভোক্তা ওয়েব ম্যানুয়াল",
    privacyPolicy: "গোপনীয়তা নীতিমালা",
    copyright: "© ২০২৬ ফুয়েলগার্ড সেতাবগঞ্জ। সর্বস্বত্ব সংরক্ষিত",
    dashboard: "ড্যাশবোর্ড",
    registry: "রেজিস্ট্রি",
    pricing: "মূল্য নির্ধারণ",
    exit: "প্রস্থান",
    logout: "লগআউট",
    allTransactions: "বিস্তারিত লেনদেনের ইতিহাস",
    filterByStation: "স্টেশন অনুযায়ী",
    filterByUser: "নাম বা নম্বর অনুযায়ী",
    manageUsers: "ইউজার ব্যবস্থাপনা",
    manageStations: "স্টেশন ব্যবস্থাপনা",
    dailyUsage: "দৈনিক ব্যবহার ও কোটা",
    monthlyUsage: "মাসিক ব্যবহার ও কোটা",
    weeklyUsage: "সাপ্তাহিক ব্যবহার",
    currentQr: "বর্তমান কিউআর কোড",
    createQr: "কিউআর কোড তৈরি করুন",
    viewAll: "সব দেখুন",
    availableStations: "উপলব্ধ ফুয়েল স্টেশনসমূহ",
    viewOnMap: "ম্যাপে দেখুন",
    lastStockUpdate: "শেষ স্টক আপডেট",
    profile: "প্রোফাইল",
    pendingApprovalTitle: "অ্যাকাউন্ট অনুমোদনের অপেক্ষায়",
    pendingApprovalDesc: "আপনার নিবন্ধন বোচাগঞ্জ উপজেলা নির্বাহী কর্মকর্তার (ইউএনও) অফিসে যাচাই করা হচ্ছে। অনুগ্রহ করে অনুমোদনের জন্য অপেক্ষা করুন।",
    waitingTime: "সাধারণত ২৪-৪৮ ঘণ্টা সময় লাগে",
    contactSupport: "ইউএনও অফিসে যোগাযোগ করুন",
    last7Days: "গত ৭ দিনের ব্যবহার",
    liters: "লিটার",
    registrationNumberShort: "রেজিঃ নং",
    manufactureYearShort: "বছর",
    vehicleClassShort: "শ্রেণী",
    houseHolding: "বাসা/হোল্ডিং",
    villageStreet: "গ্রাম/রাস্তা",
    postOffice: "ডাকঘর",
    terminal: "টার্মিনাল v3.1",
    heroTitle: "জ্বালানি নিয়ন্ত্রণ ও পর্যবেক্ষণ ব্যবস্থা",
    heroDesc: "সেতাবগঞ্জের ৫টি ফুয়েল স্টেশনে মোটরসাইকেল এবং মোটরযানের তেল ও অকটেন ব্যবহার নিয়ন্ত্রণ করা হচ্ছে।",
    terminals: "টার্মিনাল",
    nodes: "নোড",
    protocol: "প্রটোকল",
    identityTerminal: "আইডেন্টিটি টার্মিনাল",
    secureGateway: "নিরাপদ অ্যাক্সেস গেটওয়ে",
    fullIdentity: "পূর্ণ পরিচয়",
    dataIndex: "ইমেইল ঠিকানা",
    passkey: "পাসওয়ার্ড",
    authorize: "অনুমোদন করুন",
    initialize: "নিবন্ধন শুরু করুন",
    encryptionBridge: "নিরাপদ সংযোগ",
    googleSso: "গুগল এসএসও",
    newRegistry: "নতুন নিবন্ধন করুন",
    returningPersonnel: "ইতিমধ্যেই নিবন্ধিত? লগইন করুন",
    protocolGuide: "নিয়মাবলী নির্দেশিকা",
    operationalWorkflow: "কার্যপ্রণালী",
    step1Title: "পরিচয় নিবন্ধন",
    step1Desc: "ব্যবহারকারীদের এনআইডি এবং যানবাহনের তথ্য জমা দিতে হবে। কর্তৃপক্ষ জ্বালানি সংগ্রহের জন্য \"অনুমোদিত\" স্ট্যাটাস দেওয়ার আগে তথ্য যাচাই করে।",
    step2Title: "কিউআর টোকেন প্রদান",
    step2Desc: "অনুমোদিত প্রোফাইলগুলি অনন্য এনক্রিপ্টেড কিউআর টোকেন তৈরি করে। এই টোকেনগুলি গ্রাহকের তথ্য এবং সময়সীমা ডেটা বহন করে।",
    step3Title: "গতিশীল কুলডাউন",
    step3Desc: "গাণিতিক কুলডাউন লজিক: ১০০ টাকা = ১ দিন। সিস্টেম অতিরিক্ত জ্বালানি সংগ্রহ প্রতিরোধ করে এবং মজুদ ব্যবস্থাপনা নিশ্চিত করে।",
    monitoringNode: "কেন্দ্রীয় পর্যবেক্ষণ নোড",
    monitoringDesc: "সুপার এডমিনরা ৪টি পাম্প স্টেশনে সরাসরি তথ্য সমন্বয় বজায় রাখে। প্রতিটি লেনদেন যানবাহন আইডি এবং টার্মিনাল আইডি দ্বারা সংরক্ষিত হয়।",
    globalEfficiency: "সার্বিক দক্ষতা",
    uptime: "টার্মিনাল আপটাইম",
    privacy: "গোপনীয়তা নীতিমালা",
    securityAudit: "নিপারত্তা অডিট",
    requirementsTitle: "নিবন্ধনের প্রয়োজনীয় কাগজপত্র",
    reqItem1: "১। ড্রাইভিং লাইসেন্স/ গাড়ির রেজিষ্ট্রেশন এর যেকোন একটি বাধ্যতামূলক।",
    reqItem2: "২। জাতীয় পরিচয় পত্র (NID)।",
    reqItem3: "৩। পাসপোর্ট সাইজের ছবি।",
    reqItem4: "৪। ফুয়েলের আবেদনপত্রের চালকের নাম, এনআইডি, ড্রাইভিং লাইসেন্স/রেজিস্ট্রেশন পূরণ (আবেদনপত্র কম্পিউটার এর দোকানে পাওয়া যাবে)।",
    reqItem5: "৫। বোচাগঞ্জ উপজেলার বিভিন্ন ধরনের প্রতিষ্ঠানে কর্মরত হলে সেটির সপক্ষে প্রমাণাদি (আইডি কার্ড ইত্যাদি)।",
    appLocationTitle: "আবেদনপত্র জমার নির্দেশিকা",
    locMunicipality: "পৌরসভা এলাকা -> পৌরসভায় আবেদন করবেন।",
    locUnion123: "১, ২, ৩ নম্বর ইউনিয়ন -> উপজেলা নির্বাহী অফিসারের কার্যালয়ে আবেদন করবেন।",
    locUnion456: "৪, ৫, ৬ নম্বর ইউনিয়ন -> উপজেলা ভূমি অফিসে (এসি ল্যান্ড) আবেদন করবেন।",
    contactAdmin: "এডমিনের সাথে যোগাযোগ",
    adminName: "মোঃ মারুফ হাসান",
    adminTitle: "উপজেলা নির্বাহী অফিসার (ইউএনও)",
    adminMobile: "০১৭৬১-৪৯৩৫২৬",
    adminPhone: "০৫৩২৫-৭৩০০৯",
    adminEmail: "unobochaganj@gov.bd",
    supportMessenger: "সাপোর্ট মেসেঞ্জার",
    facebookProfile: "ফেসবুক প্রোফাইল",
    facebookMessengerLink: "https://www.facebook.com/messages/t/61564992836491",
    facebookProfileLink: "https://www.facebook.com/upajela.nirbahi.aphisara.bocaganja",
    myDigitalToken: "আমার ডিজিটাল টোকেন",
    readyForCollection: "সংগ্রহের জন্য প্রস্তুত",
    initializing: "শুরু হচ্ছে...",
    waitForApproval: "অনুমোদনের জন্য অপেক্ষা করুন",
    scanDescription: "এই এনক্রিপ্টেড কিউআর কোডটি ৪টি স্টেশনের যেকোনো টার্মিনালে প্রদর্শন করুন। কর্মীরা আপনার তথ্য যাচাই করে জ্বালানি প্রদান করবেন।",
    timeRemaining: "বাকি সময়",
    minutes: "মিনিট",
    scanner: "স্ক্যানার",
    admin: "এডমিন",
    logs: "লগ",
    unauthorized: "অননুমোদিত পরিচয়",
    unapprovedDesc: "আপনার ক্লিয়ারেন্স বর্তমানে অনুমোদনের অপেক্ষায় রয়েছে। ম্যানুয়াল অনুমোদনের জন্য বোচাগঞ্জ উপজেলা নির্বাহী অফিসার (ইউএনও) এর সাথে যোগাযোগ করুন।",
    systemStatus: "সিস্টেম স্ট্যাটাস: সচল",
    finalizeProfile: "নিবন্ধন প্রোফাইল সম্পন্ন করুন",
    nidNumber: "এনআইডি নম্বর",
    vehicleIndex: "যানবাহন নম্বর",
    submitProfile: "তথ্য অনুমোদন করুন",
    personnelRegistry: "কর্মী রেজিস্ট্রি",
    personnelRegistryDesc: "সকল অনুমোদিত তেলের গ্রাহক এবং লজিস্টিক কর্মীদের কেন্দ্রীয় তালিকা।",
    rankMatrix: "কর্মী র‍্যাঙ্ক ম্যাট্রিক্স",
    pricingControl: "গতিশীল মূল্য নিয়ন্ত্রণ",
    pendingApprovals: "অপেক্ষমান অনুমোদন",
    priceQuotes: "মূল্য তালিকা",
    completeRegistration: "নিবন্ধন সম্পন্ন করুন",
    vehiclePlate: "যানবাহনের লাইসেন্স নম্বর",
    platePlaceholder: "যেমন: ঢাকা-মেট্রো-ঘ-১১-২২২২",
    adminReviewNote: "দ্রষ্টব্য: টার্মিনাল সচল করার আগে কর্তৃপক্ষ আপনার তথ্য যাচাই করবে।",
    submitForApproval: "অনুমোদনের জন্য জমা দিন",
    userDigitalId: "ব্যবহারকারীর ডিজিটাল আইডি",
    approvedStatus: "অনুমোদিত",
    pendingStatus: "অপেক্ষমান",
    registryId: "রেজিস্ট্রি আইডি",
    validFrom: "কার্যকরী হয়েছে",
    scannerLogic: "স্ক্যানার লজিক",
    accessDenied: "প্রবেশাধিকার নেই",
    systemReady: "সিস্টেম প্রস্তুত",
    remaining: "বাকি",
    days: "দিন",
    awaitingApproval: "অনুমোদনের অপেক্ষায়",
    adminReviewDesc: "প্রোফাইল সচল করার আগে উপজেলা নির্বাহী অফিসার (ইউএনও) অবশ্যই তথ্য যাচাই করবেন।",
    cooldownActive: "কুলডাউন সক্রিয়",
    nextRefillOn: "পরবর্তী সংগ্রহ সম্ভব",
    ruleCooldown: "নিয়ম: ১০০ টাকা = ১ দিন সীমা",
    terminalStatus: "টার্মিনাল স্ট্যাটাস",
    active: "সক্রিয়",
    scannerHint: "তেল সংগ্রহের জন্য ডিজিটাল আইডি স্ক্যান করুন।",
    dailyPricingMatrix: "দৈনিক মূল্য তালিকা",
    octaneBdt: "অকটেন / টাকা",
    petrolBdt: "পেট্রোল / টাকা",
    dieselBdt: "ডিজেল / টাকা",
    stationTerminalControl: "স্টেশন টার্মিনাল নিয়ন্ত্রণ",
    terminalLocation: "টার্মিনাল অবস্থান",
    unassigned: "-- অনির্ধারিত --",
    activateQrScanner: "কিউআর স্ক্যানার চালু করুন",
    scanStatus: "স্ক্যান স্ট্যাটাস",
    locked: "লক করা",
    resetTerminal: "টার্মিনাল রিসেট করুন",
    refillRecorded: "লেনদেন সংগৃহীত",
    nextVehicle: "পরবর্তী যানবাহন",
    identityVerified: "পরিচয় যাচাইকৃত",
    inputAmountBdt: "টাকার পরিমাণ লিখুন",
    transmitLogRefill: "লেনদেন সম্পন্ন করুন",
    radarStandby: "রাডার স্ট্যান্ডবাই",
    waitingForScan: "টার্মিনাল স্ক্যান ইভেন্টের জন্য অপেক্ষা করা হচ্ছে...",
    statusReports: "স্ট্যাটাস রিপোর্ট",
    registryHub: "রেজিস্ট্রি হাব",
    priceConfig: "মূল্য কনফিগ",
    analytics: "অ্যানালিটিক্স",
    updatePrices: "মূল্য আপডেট করুন",
    currentPrices: "বর্তমান মূল্য",
    fuelType: "জ্বালানির ধরন",
    priceBdt: "মূল্য (টাকা)",
    userRoleHub: "ব্যবহারকারীর ভূমিকা",
    approvalQueue: "অনুমোদন সারি",
    actions: "অ্যাকশন",
    approve: "অনুমোদন দিন",
    alreadyApproved: "অনুমোদিত হয়েছে",
    role: "ভূমিকা",
    update: "আপডেট",
    changeRole: "ভূমিকা পরিবর্তন",
    userRegistry: "ব্যবহারকারী রেজিস্ট্রি",
    deleteAccount: "একাউন্ট মুছুন",
    superAdminAccess: "সুপার এডমিন অ্যাক্সেস প্রয়োজন",
    addPump: "নতুন পাম্প স্টেশন যোগ করুন",
    addressLabel: "স্টেশন ঠিকানা",
    geoLocLabel: "ভৌগলিক অবস্থান",
    syncEstLabel: "সিংক্রোনাইজেশন সময়",
    pumpName: "পাম্পের নাম",
    deliveryDate: "পরবর্তী সরবরাহের তারিখ",
    savePump: "স্টেশন সংরক্ষণ করুন",
    provisionPersonnel: "কর্মী নিয়োগ",
    emailPlaceholder: "official@station.com",
    manualAdd: "ইমেল প্রাক-অনুমোদন",
    toastSuccess: "অপারেশন সফল হয়েছে",
    toastError: "সিস্টেম ত্রুটি",
    lastDelivery: "শেষ সরবরাহ",
    offline: "অফলাইন",
    fuelPriceUpdate: "জ্বালানি মূল্য আপডেট",
    deployPricing: "মূল্য নির্ধারণ করুন",
    manualProvisioning: "ম্যানুয়াল অনুমোদন",
    grantAccess: "অ্যাক্সেস প্রদান করুন",
    stationTerminals: "স্টেশন টার্মিনাল",
    adminLogin: "এডমিন লগইন",
    userLogin: "ইউজার পোর্টাল",
    idPlaceholder: "ইমেইল / আইডি",
    passPlaceholder: "পাসওয়ার্ড",
    loginAsAdmin: "এডমিন হিসেবে লগইন করুন",
    backToUser: "ইউজার পোর্টালে ফিরুন",
    adminAccessPortal: "এডমিন অ্যাক্সেস পোর্টাল",
    allUsers: "নাগরিক নিবন্ধন তালিকা",
    transactions: "লেনদেন লগ",
    managePrices: "মূল্য পরিবর্তন",
    octanePrice: "অকটেন (প্রতি লিটার)",
    petrolPrice: "পেট্রোল (প্রতি লিটার)",
    dieselPrice: "ডিজেল (প্রতি লিটার)",
    priceUpdated: "মূল্য আপডেট করা হয়েছে",
    revokeAccess: "অ্যাক্সেস প্রত্যাহার করুন",
    confirmRevoke: "আপনি কি এই ব্যবহারকারীর অ্যাক্সেস প্রত্যাহার করতে চান?",
    filterByFuel: "জ্বালানি অনুযায়ী",
    allFuels: "সব জ্বালানি",
    octane: "অকটেন",
    petrol: "পেট্রোল",
    diesel: "ডিজেল",
    uploadProfilePhoto: "প্রোফাইল ছবি আপলোড করুন",
    changePhoto: "ছবি পরিবর্তন করুন",
    registryDetails: "বিস্তারিত তথ্য",
    userType: "ব্যবহারকারীর ধরন",
    contactInfo: "যোগাযোগের তথ্য",
    licenseInfo: "লাইসেন্স তথ্য",
    activity: "কার্যক্রম",
    systemLogs: "সিস্টেম লগ",
    latestTransactions: "সর্বশেষ লেনদেনের রেকর্ড",
    availableLimit: "অবশিষ্ট জ্বালানি সীমা",
    totalActiveVehicles: "মোট সক্রিয় যানবাহন",
    scanQr: "যানবাহন কিউআর স্ক্যান করুন",
    theme: "থিম",
    switchToLight: "লাইট মোডে সুইচ করুন",
    switchToDark: "ডার্ক মোডে সুইচ করুন",
    statusAvailable: "পর্যাপ্ত",
    successAvailable: "সফলভাবে সচল",
    driverName: "চালকের নাম",
    timestamp: "সময়",
    quantityLiters: "পরিমাণ (লিটার)",
    recentTransactionFeed: "সাম্প্রতিক লেনদেন ফিড",
    criticalSystemAlerts: "গুরুত্বপূর্ণ সিস্টেম অ্যালার্ট",
    appUptime: "অ্যাপ আপটাইম",
    latency: "ল্যাটেন্সি",
    centralMonitoringNode: "কেন্দ্রীয় পর্যবেক্ষণ নোড",
    step1Landing: "বোর্ডিং/রেজিস্ট্রেশন",
    step2Landing: "তথ্য যাচাইকরণ",
    step3Landing: "জ্বালানি সংগ্রহ ও সম্পন্ন",
    globalStatus: "সার্বিক নেটওয়ার্ক স্ট্যাটাস",
    activeNodes: "সক্রিয় নোড",
    systemPerformance: "সিস্টেমের দক্ষতা",
    viewDashboard: "ড্যাশবোর্ড দেখুন",
    vehicleRegistration: "যানবাহন নিবন্ধন",
    vehicleRegistrationSub: "সেতাবগঞ্জের পাম্পগুলোতে জ্বালানি সংগ্রহের জন্য আপনার মোটরসাইকেল বা মোটরযান নিবন্ধন করুন।",
    licensePlate: "লাইসেন্স প্লেট / রেজিঃ নং",
    engineNumber: "ইঞ্জিন নম্বর",
    chassisNumber: "চেসিস নম্বর",
    vehicleType: "যানবাহনের ধরন",
    drivingLicenseNo: "ড্রাইভিং লাইসেন্স নম্বর",
    taxTokenNo: "ট্যাক্স টোকেন / রেজিঃ কার্ড নম্বর",
    createOwnerAccount: "মালিকের অ্যাকাউন্ট তৈরি করুন",
    uploadRequiredDocs: "প্রয়োজনীয় কাগজপত্র আপলোড করুন (JPG/PNG)",
    passportPhoto: "পাসপোর্ট সাইজের ছবি",
    nidPhoto: "এনআইডি কার্ডের ছবি",
    drivingLicensePhoto: "ড্রাইভিং লাইসেন্সের ছবি",
    taxTokenPhoto: "ট্যাক্স টোকেন / রেজিঃ কার্ড"
  }
};
